import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  compileArtifactTransaction,
  validateAgentDesignSystemOutput,
  withPreAgentDesignMdRollback,
  type CompilerTransactionIo,
} from './compiler-transaction';
import { parseDesignMd, renderDesignMd, serializeDesignMd, validateAndFill } from './parse';
import { makeDocument } from './test-fixture';
import type { FontLoadingPlan } from './font-loading-plan';

const paths = {
  designMd: '/app/design/DESIGN.md',
  css: '/app/client/global.css',
  html: '/app/index.html',
  provenance: '/app/design/provenance.json',
};
const before = {
  [paths.designMd]: 'old design',
  [paths.css]: 'old css',
  [paths.html]: '<html><head><link rel="stylesheet" href="/custom-font.css"></head></html>',
  [paths.provenance]: 'old provenance',
};
const plan: FontLoadingPlan = {
  href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap',
  families: [{ cssFamilyName: 'Inter', faces: [{ weight: 400, style: 'normal' }] }],
};
const designMd = serializeDesignMd(validateAndFill(makeDocument()));

function structuredDocument() {
  const frontmatter = makeDocument();
  return {
    schemaVersion: 1 as const,
    designSystemId: frontmatter.id!,
    name: frontmatter.name,
    description: frontmatter.description,
    colors: frontmatter.colors,
    spacing: frontmatter.spacing,
    radii: frontmatter.radii,
    font: frontmatter.font,
    type: frontmatter.type,
  };
}

function memoryIo(
  fail?: (op: string, from: string, to?: string) => boolean,
): { io: CompilerTransactionIo; files: Map<string, string> } {
  const files = new Map(Object.entries(before));
  const shouldFail = (op: string, from: string, to?: string): void => {
    if (fail?.(op, from, to)) throw new Error(`injected ${op} failure`);
  };
  return {
    files,
    io: {
      exists: (path) => files.has(path),
      mkdir: () => {},
      read: (path) => {
        shouldFail('read', path);
        const value = files.get(path);
        if (value === undefined) throw new Error(`missing ${path}`);
        return value;
      },
      write: (path, content) => {
        shouldFail('write', path);
        files.set(path, content);
      },
      rename: (from, to) => {
        shouldFail('rename', from, to);
        const value = files.get(from);
        if (value === undefined) throw new Error(`missing ${from}`);
        files.delete(from);
        files.set(to, value);
      },
      remove: (path) => { files.delete(path); },
    },
  };
}

function input() {
  return {
    paths,
    designMd,
    html: before[paths.html],
    fontLoadingPlan: plan,
  };
}

function expectPriorSet(files: Map<string, string>): void {
  for (const [path, content] of Object.entries(before)) expect(files.get(path)).toBe(content);
  expect([...files.keys()].filter((path) => path.includes('.mercury-ds-'))).toEqual([]);
}

type FailureInjector = (op: string, from: string, to?: string) => boolean;
const transactionFailureCases: Array<[string, FailureInjector]> = [
  ['DESIGN.md stage write', (op, from) => op === 'write' && from.startsWith(paths.designMd)],
  [
    'HTML promotion rename',
    (op, from, to) => op === 'rename' && from.includes('.stage') && to === paths.html,
  ],
];

describe('compileArtifactTransaction', () => {
  it('replaces the ordinary starter CSS through the compiler transaction', () => {
    const starter = readFileSync(new URL('../../../apps/vite/client/global.css', import.meta.url), 'utf8');
    const seededDesign = readFileSync(new URL('../../../apps/vite/design/DESIGN.md', import.meta.url), 'utf8');
    const { io, files } = memoryIo();
    const sentinel = '/* starter-only content must disappear */';
    files.set(paths.css, `${starter}\n${sentinel}`);

    const result = compileArtifactTransaction({ ...input(), designMd: seededDesign }, io);

    expect(files.get(paths.css)).toBe(result.css);
    expect(files.get(paths.css)).not.toContain(sentinel);
    expect(files.get(paths.css)).toContain('/* GENERATED by @vibe/ds-compiler');
    expect(files.get(paths.css)).toContain('--ds-');
  });

  it('promotes the three artifacts and provenance as one validated set', () => {
    const { io, files } = memoryIo();
    const result = compileArtifactTransaction(input(), io);
    expect(files.get(paths.designMd)).toBe(designMd);
    expect(files.get(paths.css)).toBe(result.css);
    expect(files.get(paths.html)).toBe(result.html);
    expect(files.get(paths.html)).toContain('/custom-font.css');
    expect(JSON.parse(files.get(paths.provenance)!)).toEqual(result.provenance);
  });

  it('renders a structured document inside the same rollback boundary', () => {
    const { io, files } = memoryIo();
    const document = structuredDocument();
    const result = compileArtifactTransaction({
      ...input(),
      designMd: renderDesignMd(document),
    }, io);
    expect(parseDesignMd(files.get(paths.designMd)!).frontmatter.id).toBe(document.designSystemId);
    expect(files.get(paths.css)).toBe(result.css);
  });

  it.each(transactionFailureCases)('restores the prior set after an injected %s failure', (_name, fail) => {
    const { io, files } = memoryIo(fail);
    expect(() => compileArtifactTransaction(input(), io)).toThrow(/injected/);
    expectPriorSet(files);
  });

  it.each([
    ['source compilation', { designMd: 'not design markdown' }],
    ['HTML update', { html: '<html></html>' }],
  ])('leaves the prior set untouched when %s fails', (_name, invalidInput) => {
    const { io, files } = memoryIo();
    expect(() => compileArtifactTransaction({ ...input(), ...invalidInput }, io)).toThrow();
    expectPriorSet(files);
  });

  it('restores the pre-agent DESIGN.md snapshot when validation rejects an overwritten file', () => {
    const { io, files } = memoryIo();
    const different = makeDocument({ spacing: {
      ...makeDocument().spacing,
      md: '2rem',
    } });
    files.set(paths.designMd, serializeDesignMd(validateAndFill(different)));
    const priorPath = '/tmp/prior-DESIGN.md';
    files.set(priorPath, before[paths.designMd]);

    expect(() => withPreAgentDesignMdRollback(paths.designMd, priorPath, () => {
      validateAgentDesignSystemOutput(paths.designMd, structuredDocument(), io);
    }, io)).toThrow(/does not match/);

    expect(files.get(paths.designMd)).toBe(before[paths.designMd]);
    expect(files.get(priorPath)).toBe(before[paths.designMd]);
  });

  it('restores the pre-agent DESIGN.md snapshot when artifact promotion fails', () => {
    const { io, files } = memoryIo(
      (op, from, to) => op === 'rename' && from.includes('.stage') && to === paths.html,
    );
    const agentDesignMd = `${designMd}\n<!-- agent write -->\n`;
    const priorPath = '/tmp/prior-DESIGN.md';
    files.set(paths.designMd, agentDesignMd);
    files.set(priorPath, before[paths.designMd]);

    expect(() => withPreAgentDesignMdRollback(paths.designMd, priorPath, () => {
      compileArtifactTransaction({ ...input(), designMd: agentDesignMd }, io);
    }, io)).toThrow(/injected/);

    expect(files.get(paths.designMd)).toBe(before[paths.designMd]);
    expect(files.get(paths.css)).toBe(before[paths.css]);
    expect(files.get(paths.html)).toBe(before[paths.html]);
  });
});
