import { COLOR_SLOTS } from "./schema";
import type { FontSpec, RadiusScale, SpacingScale, TypeSpec } from "./parse";

export interface EmitCssInput {
  /** Semantic color tokens: slot -> bare HSL tuple `"H S% L%"`. */
  colors: Record<string, string>;
  /** Border radius, e.g. `"0.5rem"`. */
  radius: string;
  /** Full named spacing scale persisted by the design-system schema. */
  spacing: SpacingScale;
  /** Full named radius scale persisted by the design-system schema. */
  radii: RadiusScale;
  /** Font families for the sans/serif/mono theme keys. */
  font: FontSpec;
  /** Required typography scale + weights. */
  type: TypeSpec;
}

const HEADER = `/* GENERATED by @vibe/ds-compiler from DESIGN.md — do not edit by hand.
   Edit apps/vite/design/DESIGN.md and recompile (pnpm ds:compile). */`;

/**
 * Stable component recipes derived exclusively from the compiled semantic,
 * typography, spacing, and radius variables. Mercury's design-system card
 * renders the same `ds-*` class contract, so these are the generated-app form
 * of the live previews rather than a separate visual system.
 */
export const COMPONENT_RECIPES_CSS = `@layer components {
  .ds-button {
    display: inline-flex;
    min-height: 38px;
    box-sizing: border-box;
    align-items: center;
    justify-content: center;
    gap: var(--ds-space-xs);
    padding: var(--ds-space-xs) var(--ds-space-md);
    border: 1px solid transparent;
    border-radius: var(--radius-lg);
    background: transparent;
    color: var(--foreground);
    cursor: pointer;
    font-family: var(--font-label);
    font-size: var(--text-label);
    font-style: var(--font-style-label, normal);
    font-weight: var(--font-weight-label);
    line-height: var(--text-label--line-height);
    transition: background-color 120ms ease, border-color 120ms ease, color 120ms ease, box-shadow 120ms ease, transform 80ms ease;
    white-space: nowrap;
  }
  .ds-button:hover { transform: translateY(-1px); }
  .ds-button:active,
  .ds-button[aria-pressed='true'] {
    box-shadow: inset 0 0 0 1px color-mix(in srgb, currentcolor 28%, transparent);
    transform: translateY(0);
  }
  .ds-button:focus-visible,
  .ds-tab:focus-visible,
  .ds-input:focus-visible,
  .ds-menu-item:focus-visible,
  .ds-radio input:focus-visible,
  .ds-listbox-option:focus-visible {
    outline: 2px solid var(--ring);
    outline-offset: 2px;
  }
  .ds-button:disabled,
  .ds-input:disabled,
  .ds-tab:disabled,
  .ds-listbox-option:disabled {
    cursor: not-allowed;
    opacity: 0.5;
  }
  .ds-button-primary {
    background: var(--primary);
    color: var(--primary-foreground);
  }
  .ds-button-primary:hover {
    background: color-mix(in srgb, var(--primary) 88%, var(--foreground));
  }
  .ds-button-secondary {
    border-color: var(--border);
    background: var(--secondary);
    color: var(--secondary-foreground);
  }
  .ds-button-secondary:hover {
    border-color: color-mix(in srgb, var(--border) 72%, var(--foreground));
    background: var(--accent);
    color: var(--accent-foreground);
  }
  .ds-tabs {
    display: flex;
    flex-direction: column;
    gap: var(--ds-space-sm);
    color: var(--foreground);
    font-family: var(--font-body);
  }
  .ds-tab-list {
    display: flex;
    gap: var(--ds-space-sm);
    border-bottom: 1px solid var(--border);
  }
  .ds-tab {
    margin: 0;
    padding: 0 0 var(--ds-space-xs);
    border: 0;
    border-bottom: 2px solid transparent;
    background: transparent;
    color: var(--muted-foreground);
    cursor: pointer;
    font-family: var(--font-label);
    font-size: var(--text-label);
    font-style: var(--font-style-label, normal);
    font-weight: var(--font-weight-label);
    line-height: var(--text-label--line-height);
  }
  .ds-tab:hover { color: var(--foreground); }
  .ds-tab[aria-selected='true'] {
    border-bottom-color: var(--primary);
    color: var(--primary);
  }
  .ds-tab-panel {
    min-height: 1lh;
    margin: 0;
    color: var(--muted-foreground);
    font-family: var(--font-body);
    font-size: var(--text-body);
    font-style: var(--font-style-body, normal);
    font-weight: var(--font-weight-body);
    line-height: var(--text-body--line-height);
  }
  .ds-field {
    display: flex;
    flex-direction: column;
    gap: var(--ds-space-xs);
    color: var(--foreground);
  }
  .ds-field-label {
    color: var(--foreground);
    font-family: var(--font-label);
    font-size: var(--text-label);
    font-style: var(--font-style-label, normal);
    font-weight: var(--font-weight-label);
    line-height: var(--text-label--line-height);
  }
  .ds-input {
    display: block;
    min-height: 42px;
    box-sizing: border-box;
    padding: var(--ds-space-sm);
    border: 1px solid var(--input);
    border-radius: var(--radius-lg);
    background: var(--background);
    color: var(--foreground);
    font-family: var(--font-body);
    font-size: var(--text-body);
    font-style: var(--font-style-body, normal);
    font-weight: var(--font-weight-body);
    line-height: var(--text-body--line-height);
  }
  .ds-input::placeholder { color: var(--muted-foreground); }
  .ds-input:hover {
    border-color: color-mix(in srgb, var(--input) 65%, var(--foreground));
  }
  .ds-menu {
    position: relative;
    display: inline-flex;
  }
  .ds-menu-trigger[aria-expanded='true'] {
    border-color: var(--ring);
    box-shadow: 0 0 0 1px var(--ring);
  }
  .ds-menu-popover {
    position: absolute;
    z-index: 20;
    top: calc(100% + var(--ds-space-xs));
    left: 0;
    display: flex;
    min-width: 100%;
    box-sizing: border-box;
    flex-direction: column;
    gap: 2px;
    padding: var(--ds-space-xs);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    background: var(--popover);
    box-shadow: 0 10px 24px color-mix(in srgb, var(--foreground) 14%, transparent);
    color: var(--popover-foreground);
    font-family: var(--font-label, var(--font-sans));
    font-size: var(--text-label);
    font-style: var(--font-style-label, normal);
    font-weight: var(--font-weight-label);
    line-height: var(--text-label--line-height);
  }
  .ds-menu-item {
    width: 100%;
    padding: var(--ds-space-xs) var(--ds-space-sm);
    border: 0;
    border-radius: max(var(--radius-lg), 2px);
    background: transparent;
    color: inherit;
    cursor: pointer;
    font: inherit;
    text-align: left;
    white-space: nowrap;
  }
  .ds-menu-item:hover {
    background: var(--accent);
    color: var(--accent-foreground);
  }
  .ds-radio-group {
    display: flex;
    margin: 0;
    padding: 0;
    border: 0;
    flex-direction: column;
    gap: var(--ds-space-xs);
    color: var(--foreground);
  }
  .ds-radio {
    display: flex;
    align-items: center;
    gap: var(--ds-space-xs);
    color: var(--muted-foreground);
    cursor: pointer;
    font-family: var(--font-body);
    font-size: var(--text-body);
    font-style: var(--font-style-body, normal);
    font-weight: var(--font-weight-body);
    line-height: var(--text-body--line-height);
  }
  .ds-radio:has(input:checked) { color: var(--foreground); }
  .ds-radio input {
    position: relative;
    width: 16px;
    height: 16px;
    margin: 0;
    flex: none;
    border: 1.5px solid var(--border);
    border-radius: 50%;
    appearance: none;
    background: var(--background);
    cursor: pointer;
  }
  .ds-radio input:checked { border-color: var(--primary); }
  .ds-radio input:checked::after {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--primary);
    content: '';
    transform: translate(-50%, -50%);
  }
  .ds-listbox {
    display: flex;
    box-sizing: border-box;
    flex-direction: column;
    gap: 2px;
    padding: var(--ds-space-sm) var(--ds-space-md);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    background: var(--background);
    color: var(--foreground);
  }
  .ds-listbox-option {
    width: 100%;
    padding: var(--ds-space-xs) var(--ds-space-sm);
    border: 0;
    border-radius: max(var(--radius-lg), 2px);
    background: transparent;
    color: var(--foreground);
    cursor: pointer;
    font-family: var(--font-body, var(--font-sans));
    font-size: var(--text-body);
    font-style: var(--font-style-body, normal);
    font-weight: var(--font-weight-body);
    line-height: var(--text-body--line-height);
    text-align: left;
  }
  .ds-listbox-option:hover { background: var(--muted); }
  .ds-listbox-option[aria-selected='true'] {
    background: var(--accent);
    color: var(--accent-foreground);
  }
}`;

/**
 * Emit the Tailwind v4 global.css from already-resolved tokens.
 *
 * Output shape mirrors apps/vite/client/global.css: imports, @source, the
 * class-based dark variant, :root, @theme inline (colors, radius scale, fonts,
 * spacing, optional type scale/weights, animations), the four @keyframes, and
 * the @layer base block.
 * Every color value is hsl()-wrapped so the file never contains a raw hex.
 */
export function emitCss({
  colors,
  radius,
  spacing,
  radii,
  font,
  type,
}: EmitCssInput): string {
  const authoredSlots = COLOR_SLOTS.filter((slot) => colors[slot] !== undefined);
  const rootVars = authoredSlots.map(
    (slot) => `  --${slot}: hsl(${colors[slot]});`,
  ).join("\n");

  const themeColors = authoredSlots.map(
    (slot) => `  --color-${slot}: var(--${slot});`,
  ).join("\n");

  const quoteCssFamily = (family: string): string =>
    `"${family.replace(/"/g, '\\"')}"`;

  const fontReferenceVars = Object.keys(font)
    .sort()
    .map((key) => `  --ds-font-${key}: ${quoteCssFamily(font[key].cssFamilyName)}, ${font[key].fallback};`)
    .join("\n");

  const typeVars = Object.keys(type.scale)
    .sort()
    .flatMap((key) => {
      const step = type.scale[key];
      return [
        `  --text-${key}: ${step.fontSize};`,
        `  --text-${key}--line-height: ${step.lineHeight};`,
        ...(step.letterSpacing
          ? [`  --text-${key}--letter-spacing: ${step.letterSpacing};`]
          : []),
        `  --font-${key}: var(--ds-font-${step.fontKey});`,
        ...(step.fontStyle
          ? [`  --font-style-${key}: ${step.fontStyle};`]
          : []),
      ];
    })
    .join("\n");

  const weightVars = Object.keys(type.weights)
    .sort()
    .map((key) => `  --font-weight-${key}: ${type.weights[key]};`)
    .join("\n");

  const spacingRootVars = Object.keys(spacing)
    .sort()
    .map((key) => `  --ds-space-${key}: ${spacing[key as keyof SpacingScale]};`)
    .join("\n");

  // Tailwind v4 reserves the --spacing-* namespace for every spacing-derived
  // utility, including max-w-*, size-*, padding, margin, and gap. Prefix the
  // authored rhythm scale so `max-w-xl` keeps Tailwind's normal 36rem meaning
  // while authored rhythm remains available as p-ds-xl, gap-ds-md, and so on.
  const spacingThemeVars = Object.keys(spacing)
    .sort()
    .map((key) => `  --spacing-ds-${key}: var(--ds-space-${key});`)
    .join("\n");

  const radiusVars = Object.keys(radii)
    .sort()
    .map((key) => `  --radius-${key}: ${radii[key as keyof RadiusScale]};`)
    .join("\n");

  const typeBlock = typeVars ? `\n\n${typeVars}` : "";
  const defaultFontBlock = type.scale.body
    ? "\n\n  --font-sans: var(--font-body);"
    : "";
  const weightBlock = weightVars ? `\n\n${weightVars}` : "";
  const typeUtilities = Object.keys(type.scale)
    .sort()
    .map((key) => {
      const step = type.scale[key];
      const weight = type.weights[key];
      return `  .type-${key} {
    font-family: var(--font-${key});
    font-size: var(--text-${key});
    line-height: var(--text-${key}--line-height);${step.letterSpacing ? `\n    letter-spacing: var(--text-${key}--letter-spacing);` : ""}${step.fontStyle ? `\n    font-style: var(--font-style-${key});` : ""}${weight !== undefined ? `\n    font-weight: var(--font-weight-${key});` : ""}
  }`;
    })
    .join("\n");
  // Components layer, after the recipes: a role class overrides `ds-*` recipe
  // typography, and any Tailwind utility on the same element (`text-7xl`,
  // `font-black`, a panel edit) overrides the role — Tailwind orders
  // `components` below `utilities` regardless of source order.
  const typeUtilitiesBlock = typeUtilities
    ? `\n@layer components {\n${typeUtilities}\n}`
    : "";

  return `${HEADER}
@import 'tailwindcss';
@import 'tw-animate-css';

/* v4 scans source text, not the module graph. The CSS file lives at
   apps/vite/client/global.css (client/ -> vite/ -> apps/ -> root), so
   packages/ui/src is three levels up. Without this, @vibe/ui classes drop. */
@source '../../../packages/ui/src';
@custom-variant dark (&:is(.dark *));
:root {
${rootVars}
  --radius: ${radius};
${spacingRootVars}
${fontReferenceVars ? `\n${fontReferenceVars}` : ""}
}
@theme inline {
${themeColors}

${radiusVars}

${spacingThemeVars}${typeBlock}${defaultFontBlock}${weightBlock}

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;
  --animate-fade-in: fade-in 0.4s ease-out;
  --animate-shimmer: shimmer 2s linear infinite;
}

@keyframes accordion-down {
  from { height: 0; }
  to { height: var(--radix-accordion-content-height); }
}
@keyframes accordion-up {
  from { height: var(--radix-accordion-content-height); }
  to { height: 0; }
}
@keyframes fade-in {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes shimmer {
  from { background-position: 0 0; }
  to { background-position: -200% 0; }
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }
}
${COMPONENT_RECIPES_CSS}
${typeUtilitiesBlock}
`;
}
